### PR TITLE
Blueprint Port

### LINKED ISSUE #335: GNOME - Port to Blueprint

### PR DESCRIPTION
**Pull request by DaPigGuy**
This ought to be "fun"

**TODO**
- [x] GroupRow
- [x] PasswordDialog
- [x] TransactionRow
- [x] AccountSettingsDialog
- [x] AccountView
  - The constructor is 429 lines :cold_sweat: 
- [x] GroupDialog
- [x] MainWindow
- [x] PreferencesDialog
- [x] ShortcutsDialog
- [x] TransactionDialog
- [x] TransferDialog 

Fixes #335

### CODE REVIEW

**Comment by DaPigGuy** [comment]
Considering how much more there is to the Denaro UI vs. Tube Converter, we might want to dedicate a beta release to making sure nothing broke

**Comment by nlogozzo** [comment]
@fsobolev How does it look to you?

**Review by nlogozzo — CHANGES_REQUESTED** [review]
Just a few issues:
- [x] Toggling the filter of a GroupRow seems to have no effect:
- [ ] There is this weird line when scrolled to the top of the transactions list under the `Transactions` label:
image

Otherwise seems to function great :)

**Comment by DaPigGuy** [comment]
>  There is this weird line when scrolled to the top of the transactions list under the Transactions label:

That line should appear when hitting the "top" when scrolling upwards, I believe that comes from libadwaita. It matches the stable release, at least for me  :sweat_smile:

**Comment by nlogozzo** [comment]
> That line should appear when hitting the top when scrolling upwards, I believe that comes from libadwaita. It matches the stable release, at least for me  :sweat_smile: 

Yes, but the problem is it doesn't go away and stays there constantly. Could just be a WSL artifact render issue

**Comment by DaPigGuy** [comment]
It could be. For me, it only stays for as long as I hold the scroll up touchpad gesture

**Comment by nlogozzo** [comment]
https://user-images.githubusercontent.com/17648453/223803317-070fec4f-fbe0-4860-ab27-7e3b03f41ff1.mp4

Yeah definitely probably a weird WSL GPU thing

**Review by nlogozzo — APPROVED** [review]

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.3.0-beta1

**Pull request merged**
