### PR TITLE
Password Protect PDF

### LINKED ISSUE #273: Password-Protect Export PDF File
Ask the user if they would like to provide a password to lock a PDF file when one is being exported.

### PR DESCRIPTION
**Pull request by nlogozzo**
Asks the user if they'd like to password-protect their pdf.

Closes #273 

## TODO
- [x] Backend implementation
- [x] WinUI implementation
- [x] GNOME implementation

### CODE REVIEW

**Comment by nlogozzo** [comment]
WinUI Implementation

https://user-images.githubusercontent.com/17648453/225385611-dbb13ab9-5d80-4a75-b1f0-73e7ab301526.mp4

**Comment by nlogozzo** [comment]
@fsobolev Can you test the GNOME implementation? Once I click yes on the `Add Password To PDF?` dialog, the `NewPasswordDialog` doesn't show. I don't know if it's a WSL thing or something in the implementation...

**Comment by fsobolev** [comment]
It indeed doesn't show, there's `(NickvisionMoney.GNOME:2): Gdk-WARNING **: 21:25:36.737: gdk_gl_context_make_current() failed` and then the app crashes.

**Comment by nlogozzo** [comment]
> It indeed doesn't show, there's `(NickvisionMoney.GNOME:2): Gdk-WARNING **: 21:25:36.737: gdk_gl_context_make_current() failed` and then the app crashes.

Ok, i think I found a better way to show it...let me try that

**Review by fsobolev — APPROVED** [review]

**Pull request merged**
