### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by fsobolev**
Thanks for the app! :heart: Just found it recently and I'm glad I can now contribute with translation. Unfortunately I experienced some crashes when ~~creating new account~~ (it happened a few times, but I can't reproduce it anymore) and importing from CSV while running the app in GNOME Builder (latest version installed from Flathub works fine), so I can't verify a few lines, yet I think it should be okay.

### CODE REVIEW

**Comment by nlogozzo** [comment]
The master branch is always being developed, so issues are expected. Can you send me the CSV file you were trying to import that crashed the app. I will look into it.

**Comment by nlogozzo** [comment]
However, please open a new issue and upload the CSV file there as this PR would just be for the translation.

**Comment by nlogozzo** [comment]
Please update the translation to the new translation context seen in https://github.com/nlogozzo/NickvisionMoney/pull/17

**Comment by fsobolev** [comment]
Done 👌🏻

**Comment by nlogozzo** [comment]
LGTM! Thanks :)

**Pull request merged**
