### PR TITLE
Show Number Of Filtered Transactions

### PR DESCRIPTION
**Pull request by nlogozzo**
This PR modifies the `Transactions` group title to show the number of transactions being shown based of the current filters.

## GNOME
image
image
image

## WinUI
image

### CODE REVIEW

**Review by fsobolev — CHANGES_REQUESTED** [review]
This can't be naturally translated. "2 транзакц**ии**", "5 транзакц**ий**", "21 транзакц**ия**"...
Simply "Transactions (N)" will be better.

**Comment by fsobolev** [comment]
On the other hand... If source `Transactions` string will be "{0} Transactions", then I will be able to translate it as "Транзакции ({0})"

**Comment by nlogozzo** [comment]
> On the other hand... If source Transactions string will be "{0} Transactions", then I will be able to translate it as "Транзакции ({0})". Same for Transaction ("{0} Transaction"), better let translators format it.

Ok, this is how I implemented it. https://github.com/nlogozzo/NickvisionMoney/pull/379/commits/261274d01a790defd04d90dfac74786d3fdcd436

**Comment by nlogozzo** [comment]
> This can't be naturally translated. "2 транзакц**ии**", "5 транзакц**ий**", "21 транзакц**ия**"... Simply "Transactions (N)" will be better.

Forgot we had this conversation 😅

**Review by fsobolev — APPROVED** [review]

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.4.0-beta1

**Pull request merged**
