### PR TITLE
Add gressource search path relative to exe closes #137

### LINKED ISSUE #137: Trying to package for NixOS SIGSEGV
Hello,
I am trying to package this for NixOS but I am sadly getting a sigsev error in libgio-2 after it compiled successfully.
There is a high chance this is no error with money but I thought maybe someone knows what is happening.
So i am trying to create the package with the following derivation:

```nix
{ stdenv
, lib
, fetchFromGitHub
, meson
, ninja
, cmake
, pkg-config
, binutils
, gtk4
, libadwaita
, glib
, jsoncpp
, sqlitecpp
, sqlite
, boost
, desktop-file-utils
, shared-mime-info
}:

stdenv.mkDerivation rec {
  pname = "money";
  version = "2022.11.1";

  src = fetchFromGitHub {
    owner = "nlogozzo";
    repo = "NickvisionMoney";
    rev = "02e8ab5e9422e7690522ed496d6412e886488f0b";
    sha256 = "lW3ap2tK75gcMfi5hv4UQoxzwh6AydrikoXPkMuXwDE=";
  };

  nativeBuildInputs = [
    meson
    cmake
    pkg-config
    ninja
  ];

  buildInputs = [
    binutils
    libadwaita
    gtk4
    glib
    jsoncpp
    sqlitecpp
    sqlite
    boost
    desktop-file-utils
    shared-mime-info
  ];

  # https://github.com/NixOS/nixpkgs/issues/86131
  BOOST_INCLUDEDIR = "${lib.getDev boost}/include";
  BOOST_LIBRARYDIR = "${lib.getLib boost}/lib";

  #PKG_CONFIG_PATH = lib.makeSearchPath "lib/pkgconfig" buildInputs;
  #LD_LIBRARY_PATH = lib.makeLibraryPath buildInputs;

  meta = with lib; {
    license = licenses.gpl3;
    maintainers = with maintainers; [ mordrag ];
    description = "A personal finance manager ";
    platforms = platforms.linux;
  };
}
```

This compiles successfully but when running the executable the following error occurs:

```
Module libGLX.so.0 without build-id.
Module libXdmcp.so.6 without build-id.
Module libXau.so.6 without build-id.
Module libGLdispatch.so.0 without build-id.
Module libdatrie.so.1 without build-id.
Module libpcre.so.1 without build-id.
Module libdeflate.so.0 without build-id.
Module liblzma.so.5 without build-id.
Module libxml2.so.2 without build-id.
Module libjson-glib-1.0.so.0 without build-id.
Module libexpat.so.1 without build-id.
Module libbz2.so.1 without build-id.
Module libGL.so.1 without build-id.
Module libXrender.so.1 without build-id.
Module libxcb-render.so.0 without build-id.
Module libxcb.so.1 without build-id.
Module libxcb-shm.so.0 without build-id.
Module libEGL.so.1 without build-id.
Module libgraphite2.so.3 without build-id.
Module libfreetype.so.6 without build-id.
Module libthai.so.0 without build-id.
Module libicuuc.so.72 without build-id.
Module libicui18n.so.72 without build-id.
Module libicudata.so.72 without build-id.
Module libboost_chrono.so.1.79.0 without build-id.
Module libboost_thread.so.1.79.0 without build-id.
Module libboost_system.so.1.79.0 without build-id.
Module libpcre2-8.so.0 without build-id.
Module libffi.so.8 without build-id.
Module libselinux.so.1 without build-id.
Module libz.so.1 without build-id.
Module libXinerama.so.1 without build-id.
Module libXrandr.so.2 without build-id.
Module libXfixes.so.3 without build-id.
Module libXdamage.so.1 without build-id.
Module libXcursor.so.1 without build-id.
Module libXext.so.6 without build-id.
Module libxkbcommon.so.0 without build-id.
Module libjpeg.so.62 without build-id.
Module libtiff.so.5 without build-id.
Module libpng16.so.16 without build-id.
Module libtracker-sparql-3.0.so.0 without build-id.
Module libpangoft2-1.0.so.0 without build-id.
Module libX11.so.6 without build-id.
Module libXi.so.6 without build-id.
Module libepoxy.so.0 without build-id.
Module libfontconfig.so.1 without build-id.
Module libharfbuzz.so.0 without build-id.
Module libpangocairo-1.0.so.0 without build-id.
Module libgraphene-1.0.so.0 without build-id.
Module libpango-1.0.so.0 without build-id.
Module libfribidi.so.0 without build-id.
Module libgcc_s.so.1 without build-id.
Module libstdc++.so.6 without build-id.
Module libboost_locale.so.1.79.0 without build-id.
Module libjsoncpp.so.24 without build-id.
Module libadwaita-1.so.0 without build-id.
Module org.nickvision.money without build-id.
Stack trace of thread 18341:
#0  0x00007ffff7505f43 g_resource_ref (libgio-2.0.so.0 + 0x9ef43)
#1  0x00007ffff7507051 g_resources_register (libgio-2.0.so.0 + 0xa0051)
#2  0x000000000043f4cd _ZN15NickvisionMoney2UI11ApplicationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE17GApplicationFlags (org.nickvision.money + 0x3f4cd)
#3  0x000000000041492c main (org.nickvision.money + 0x1492c)
#4  0x00007ffff6b7024e __libc_start_call_main (libc.so.6 + 0x2924e)
#5  0x00007ffff6b70309 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x29309)
#6  0x0000000000414c55 _start (org.nickvision.money + 0x14c55)
ELF object binary architecture: AMD x86-64
```

And lldb says

```
Process 18341 launched: '/etc/profiles/per-user/tom/bin/org.nickvision.money' (x86_64)
Process 18341 stopped
* thread #1, name = 'org.nickvision.', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x00007ffff7505f43 libgio-2.0.so.0`g_resource_ref + 3
libgio-2.0.so.0`g_resource_ref:
->  0x7ffff7505f43 <+3>: lock   
    0x7ffff7505f44 <+4>: addl   $0x1, (%rdi)
    0x7ffff7505f47 <+7>: retq   
    0x7ffff7505f48:      nopl   (%rax,%rax)
```

### PR DESCRIPTION
**Pull request by MordragT**
Hi this is fixing my issues I explained in #137 .
Maybe there is a better way to fix this issue, I am not usually writing cpp.
But I wanted to show a way how this could be fixed :).

### CODE REVIEW

**Comment by fsobolev** [comment]
Maybe it's not needed to look in "/usr/share/..." and "/app/share/..." then?

**Comment by MordragT** [comment]
Yes probably if the app is always installed in "/usr/bin" respectively "/app/bin"

**Comment by fsobolev** [comment]
Just tested in GNOME Builder:
```
    auto exeDir = std::filesystem::canonical("/proc/self/exe");
    auto resDir = exeDir
        .parent_path()
        .parent_path()
        .concat("/share/org.nickvision.money/org.nickvision.money.gresource")
        .string();

    //Load Resource
    g_resources_register(g_resource_load(resDir.c_str(), nullptr));
```

Works fine. No need to look for other paths.

**Comment by MordragT** [comment]
Should I change the PR to load always the relative path to the exe ?

**Comment by fsobolev** [comment]
Yes, please

**Comment by fsobolev** [comment]
Or wait, will it work in your case to look in the `XDG_DATA_HOME` instead of `../../share`? I think it would be better then

**Comment by MordragT** [comment]
Yes I dont know if it works to install the ressource file inside XDG_DATA_HOME in the meson file, as another user will have trouble running the application but maybe XDG_DATA_DIRS may work ? But I am not convinced it is the best solution.

**Review by fsobolev — APPROVED** [review]

**Comment by nlogozzo** [comment]
The only thing about the code I would comment about is `auto`. This C++ codebase doesn't really like the use of `auto`.

But speaking that we are actively rewriting the whole application to C#, i'll let it slide since it's going to be rewritten anyway :)

**Pull request merged**
