### PR TITLE
Update Description

### PR DESCRIPTION
**Pull request by nlogozzo**
To be merged after V2023.4.0 stable release.

### CODE REVIEW

**Comment by fsobolev** [comment]
Why after and why change long description at all? It matches short description here

**Comment by nlogozzo** [comment]
> Why after

Requires translation change. RC1 signifies string freeze

> why change long description at all? It matches short description here

Ones not really longer then the other, they're the same size. And the "short" one sounds a lot better IMO.

**Comment by fsobolev** [comment]
> Requires translation change. RC1 signifies string freeze

That string existed before RC1, because it was the short description, so translations can be copy-pasted https://github.com/nlogozzo/NickvisionMoney/blob/main/NickvisionMoney.Shared/Resources/Strings.resx#L1146

> And the "short" one sounds a lot better IMO.

Well I agree it sounds better, and it's great short description. But I don't like that we have the same long and short descriptions 😞

**Comment by nlogozzo** [comment]
> That string existed before RC1, because it was the short description, so translations can be copy-pasted

Ah ok, i'll go through translations and update them when I get a chance...won't be till later tomorrow as I have an exam in the morning 🙄

> EDIT: Suggestion for long description (metainfo-only, in doap long description is not necessary I think):

Looks good to me. Feel free to commit it in the metainfo. Feel free to make one for Tube Converter and I'll go through those translations too tomorrow.

**Comment by fsobolev** [comment]
> Looks good to me. Feel free to commit it in the metainfo.

Great, thanks! I will also update `_translate-meta` recipe in justfile, because currently it inserts text using string numbers, which is not the best way to handle it.

**Comment by nlogozzo** [comment]
Ok i updated the descriptions for translations that had `Summary.GTK` translated. If `Summary.GTK` was not translated for a language, that language's translation was left untouched.

**Comment by nlogozzo** [comment]
> EDIT: Suggestion for long description (metainfo-only, in doap long description is not necessary I think):

Committed.

**Comment by nlogozzo** [comment]
Reverted the commit because the script that translates this description needs to be updated to support a new list.

**Comment by fsobolev** [comment]
@nlogozzo metainfo should be good now. I renamed `Summary.GTK` to `MetadataDescription.GTK` because it's the only place when the long description is used (feel free to change if you want to use it for WinUI somewhere), keeping old values except for English and Russian. Script was changed to be more intelligent (it doesn't rely on string numbers or the content of an element, can be a simple text like in most translations now or another tree) and the generated file passes relaxed validation (regular validation gives the same errors as without the changes).

**Comment by nlogozzo** [comment]
Thank you :) Will merge after V2023.4.0 stable is released at 12:00 AM EST tonight since we changed strings. 

Feel free to update the scripts in Application and Tube Converter and add a long description for them

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.4.1-beta1

**Pull request merged**
