### PR TITLE
Updated Croatian PO file with plural forms

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by zothma** [comment]
You should remove everything from line 415, because those entries are no longer in the app

**Comment by nlogozzo** [comment]
Could you resolve conflicts. This occurred after merging #62 .

**Comment by milotype** [comment]
@nlogozzo What conflicts need to be resolved? Please specify. I don't understand the problem.

**Comment by nlogozzo** [comment]
I commited it here: https://github.com/nlogozzo/NickvisionMoney/commit/20a5c0f36bf615c2bc36509b16545ff993a7aa43

**Pull request closed without merging**
