### PR TITLE
Update translations and update hi.po

### PR DESCRIPTION
**Pull request by heymisphere**

### CODE REVIEW

**Comment by nlogozzo** [comment]
Is this for the latest commit (https://github.com/nlogozzo/NickvisionMoney/commit/0e114ef6b5578b23e32ba5e4d794e3f43e3e1aee) ?

**Comment by heymisphere** [comment]
> Is this for the latest commit ([0e114ef](https://github.com/nlogozzo/NickvisionMoney/commit/0e114ef6b5578b23e32ba5e4d794e3f43e3e1aee)) ?

yes

**Comment by nlogozzo** [comment]
You work fast! 😄

**Comment by nlogozzo** [comment]
@milotype @Vistaus @zothma @heymisphere @bordam @martin-desktops @fsobolev 
Please update po files for the new transfer feature :) Submit translations by tomorrow (11/24) night (11:59 PM EST) so we can release the stable version by Friday.
Money V2022.11.1 is now in feature freeze so this should be the last time you need to update translations before the stable release :)

**Comment by heymisphere** [comment]
> You work fast! smile

I just check your repository daily, and today when I checked, you just pushed the last commit some seconds ago, so I did the work

**Pull request merged**
